# --- !Ups
ALTER TABLE route ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();
CREATE INDEX route_user_id_idx ON route (user_id);

-- Routes predating user-supplied names were all saved with the placeholder name "temp". Give them a
-- presentable default so they can be listed in the new dashboard "My Routes" section.
UPDATE route SET name = 'Route ' || route_id WHERE name = 'temp';

-- Explicit street ordering so saved routes can be edited in place. Ordering was previously implicit in the
-- serial route_street_id, which breaks once an update inserts a street mid-route (new rows always get higher ids).
ALTER TABLE route_street ADD COLUMN position INT;
UPDATE route_street
SET position = numbered.rn - 1
FROM (
    SELECT route_street_id, ROW_NUMBER() OVER (PARTITION BY route_id ORDER BY route_street_id) AS rn
    FROM route_street
) numbered
WHERE route_street.route_street_id = numbered.route_street_id;
ALTER TABLE route_street ALTER COLUMN position SET NOT NULL;

-- Auto-routed out-and-back routes legitimately traverse the same street twice (once per direction), so the
-- street-based natural key from 338 is too strict -- the real per-route natural key is the walking-order position.
ALTER TABLE route_street DROP CONSTRAINT route_street_route_id_street_edge_id_key;
ALTER TABLE route_street ADD CONSTRAINT route_street_route_id_position_key UNIQUE (route_id, position);

-- Semantic share slugs derived from the route's name, unique per city. Runtime slugs are generated by
-- SlugUtils.slugify, which collapses separator runs so a slug can never contain '--'. The backfill exploits that
-- invariant when deduping candidates below, suffixing '--<route_id>' so a literal name like "Park Walk 2" cannot
-- collide with the deduped slug of a second "Park Walk" route.
ALTER TABLE route ADD COLUMN slug TEXT;
UPDATE route
SET slug = CASE WHEN deduped.rn = 1 THEN deduped.candidate ELSE deduped.candidate || '--' || deduped.route_id END
FROM (
    SELECT route_id, candidate, ROW_NUMBER() OVER (PARTITION BY candidate ORDER BY route_id) AS rn
    FROM (
        SELECT route_id,
               COALESCE(NULLIF(btrim(left(regexp_replace(lower(name), '[^[:alnum:]]+', '-', 'g'), 60), '-'), ''),
                        'route-' || route_id) AS candidate
        FROM route
    ) candidates
) deduped
WHERE route.route_id = deduped.route_id;
ALTER TABLE route ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX route_slug_idx ON route (slug);

-- Optional public description shown alongside the route (why the route matters to its creator).
ALTER TABLE route ADD COLUMN description TEXT;

-- Old slugs of renamed routes, kept so previously shared /r/<slug> links redirect forever.
CREATE TABLE route_slug_alias (
    slug TEXT PRIMARY KEY,
    route_id INT NOT NULL REFERENCES route(route_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE route_slug_alias OWNER TO sidewalk;

# --- !Downs
DROP TABLE route_slug_alias;
ALTER TABLE route DROP COLUMN description;
DROP INDEX route_slug_idx;
ALTER TABLE route DROP COLUMN slug;
ALTER TABLE route_street DROP CONSTRAINT route_street_route_id_position_key;
ALTER TABLE route_street ADD CONSTRAINT route_street_route_id_street_edge_id_key UNIQUE (route_id, street_edge_id);
ALTER TABLE route_street DROP COLUMN position;
DROP INDEX route_user_id_idx;
ALTER TABLE route DROP COLUMN created_at;
