# --- !Ups
ALTER TABLE route ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();
CREATE INDEX route_user_id_idx ON route (user_id);

-- Routes predating user-supplied names were all saved with the placeholder name "temp". Give them a
-- presentable default so they can be listed in the new dashboard "My Routes" section.
UPDATE route SET name = 'Route ' || route_id WHERE name = 'temp';

-- Explicit street ordering so saved routes can be edited in place. Ordering was previously implicit in the
-- serial route_street_id, which breaks once an update inserts a street mid-route (new rows always get higher ids).
ALTER TABLE route_street ADD COLUMN position INT;
UPDATE route_street
SET position = numbered.rn - 1
FROM (
    SELECT route_street_id, ROW_NUMBER() OVER (PARTITION BY route_id ORDER BY route_street_id) AS rn
    FROM route_street
) numbered
WHERE route_street.route_street_id = numbered.route_street_id;
ALTER TABLE route_street ALTER COLUMN position SET NOT NULL;
-- Walking order is a zero-based ordinal (backfilled rn - 1, written from zipWithIndex).
ALTER TABLE route_street ADD CONSTRAINT route_street_position_check CHECK (position >= 0);

-- Auto-routed out-and-back routes legitimately traverse the same street twice (once per direction), so the
-- street-based natural key from 338 is too strict -- the real per-route natural key is the walking-order position.
ALTER TABLE route_street DROP CONSTRAINT route_street_route_id_street_edge_id_key;
ALTER TABLE route_street ADD CONSTRAINT route_street_route_id_position_key UNIQUE (route_id, position);

-- Semantic share slugs derived from the route's name, unique per city. Runtime slugs are generated by
-- SlugUtils.slugify, which collapses separator runs so a slug can never contain '--'. The backfill exploits that
-- invariant when deduping candidates below, suffixing '--<route_id>' so a literal name like "Park Walk 2" cannot
-- collide with the deduped slug of a second "Park Walk" route.
ALTER TABLE route ADD COLUMN slug TEXT;
UPDATE route
SET slug = CASE WHEN deduped.rn = 1 THEN deduped.candidate ELSE deduped.candidate || '--' || deduped.route_id END
FROM (
    SELECT route_id, candidate, ROW_NUMBER() OVER (PARTITION BY candidate ORDER BY route_id) AS rn
    FROM (
        SELECT route_id,
               COALESCE(NULLIF(btrim(left(regexp_replace(lower(name), '[^[:alnum:]]+', '-', 'g'), 60), '-'), ''),
                        'route-' || route_id) AS candidate
        FROM route
    ) candidates
) deduped
WHERE route.route_id = deduped.route_id;
ALTER TABLE route ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX route_slug_idx ON route (slug);

-- Optional public description shown alongside the route (why the route matters to its creator).
ALTER TABLE route ADD COLUMN description TEXT;

-- Display stats for route listings. Deriving them per request meant re-running ST_Transform + ST_Length over
-- every street of every route on each dashboard and RouteBuilder load, and they only change when the street
-- list does, so RouteService writes them there. The inner join that derivation needed also hid street-less
-- routes from their own owner. CHECK allows 0 because routes predating the non-empty-street-list rule may
-- have none.
ALTER TABLE route ADD COLUMN distance_meters DOUBLE PRECISION;
ALTER TABLE route ADD COLUMN street_count INT;
UPDATE route
SET distance_meters = stats.distance_meters, street_count = stats.street_count
FROM (
    SELECT route.route_id,
           SUM(ST_Length(ST_Transform(street_edge.geom, 26918))) AS distance_meters,
           COUNT(*) AS street_count
    FROM route
    INNER JOIN route_street ON route.route_id = route_street.route_id
    INNER JOIN street_edge ON route_street.street_edge_id = street_edge.street_edge_id
    GROUP BY route.route_id
) stats
WHERE route.route_id = stats.route_id;
UPDATE route SET distance_meters = 0, street_count = 0 WHERE distance_meters IS NULL;
ALTER TABLE route ALTER COLUMN distance_meters SET NOT NULL;
ALTER TABLE route ALTER COLUMN street_count SET NOT NULL;
ALTER TABLE route ADD CONSTRAINT route_distance_meters_check CHECK (distance_meters >= 0);
ALTER TABLE route ADD CONSTRAINT route_street_count_check CHECK (street_count >= 0);

-- Old slugs of renamed routes, kept so previously shared /r/<slug> links redirect forever.
CREATE TABLE route_slug_alias (
    slug TEXT PRIMARY KEY,
    route_id INT NOT NULL REFERENCES route(route_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE route_slug_alias OWNER TO sidewalk;

-- One mission per route walk: a mission created for a route session is scoped to that traversal (user_route),
-- sized to the route's full length, and completed when the route is. Region missions leave this null, and the
-- two pools never resume each other's missions.
ALTER TABLE mission ADD COLUMN user_route_id INT REFERENCES user_route(user_route_id);
-- Partial index: only route-scoped missions are looked up by user_route_id, and they're a tiny fraction of the
-- (large) mission table. Slick has no DSL for partial indexes, so this lives only in the evolution.
CREATE INDEX mission_user_route_id_idx ON mission (user_route_id) WHERE user_route_id IS NOT NULL;

# --- !Downs
ALTER TABLE mission DROP COLUMN user_route_id;
DROP TABLE route_slug_alias;
ALTER TABLE route DROP COLUMN street_count;
ALTER TABLE route DROP COLUMN distance_meters;
ALTER TABLE route DROP COLUMN description;
DROP INDEX route_slug_idx;
ALTER TABLE route DROP COLUMN slug;
ALTER TABLE route_street DROP CONSTRAINT route_street_route_id_position_key;
ALTER TABLE route_street DROP CONSTRAINT route_street_position_check;
-- The Ups exist to allow a route to traverse a street twice (out-and-back), so real rows violate the constraint
-- being restored. Collapse each (route_id, street_edge_id) to its earliest row first, dropping the progress links
-- that reference the rows going away.
DELETE FROM audit_task_user_route
WHERE route_street_id IN (
    SELECT route_street_id FROM route_street
    WHERE route_street_id NOT IN (
        SELECT MIN(route_street_id) FROM route_street GROUP BY route_id, street_edge_id
    )
);
DELETE FROM route_street
WHERE route_street_id NOT IN (
    SELECT MIN(route_street_id) FROM route_street GROUP BY route_id, street_edge_id
);
ALTER TABLE route_street ADD CONSTRAINT route_street_route_id_street_edge_id_key UNIQUE (route_id, street_edge_id);
ALTER TABLE route_street DROP COLUMN position;
DROP INDEX route_user_id_idx;
ALTER TABLE route DROP COLUMN created_at;
