
# --- !Ups
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27047 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27048 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27049 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27089 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27053 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27054 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27055 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27056 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27057 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27058 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27061 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27062 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27063 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27064 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27066 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27069 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27070 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27071 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27073 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27074 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27084 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27085 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27086 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27088 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27091 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27092 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27093 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27094 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27095 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27096 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27097 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27098 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27099 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27102 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27103 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27104 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27105 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27106 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27107 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27108 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27109 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27110 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27111 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27112 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27113 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27114 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27115 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27116 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27117 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27118 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27119 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27120 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27123 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27124 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27127 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27128 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27129 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27130 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27100 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27131 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27132 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27133 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27134 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27135 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27136 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27137 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27138 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27139 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27140 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27141 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27143 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27144 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27145 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27146 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27147 );
INSERT INTO street_edge_assignment_count (street_edge_id) VALUES ( 27101 );

# --- !Downs
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27047;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27048;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27049;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27089;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27053;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27054;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27055;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27056;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27057;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27058;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27061;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27062;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27063;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27064;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27066;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27069;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27070;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27071;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27073;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27074;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27084;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27085;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27086;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27088;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27091;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27092;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27093;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27094;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27095;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27096;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27097;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27098;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27099;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27102;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27103;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27104;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27105;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27106;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27107;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27108;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27109;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27110;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27111;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27112;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27113;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27114;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27115;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27116;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27117;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27118;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27119;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27120;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27123;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27124;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27127;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27128;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27129;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27130;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27100;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27131;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27132;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27133;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27134;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27135;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27136;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27137;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27138;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27139;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27140;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27141;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27143;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27144;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27145;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27146;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27147;
DELETE FROM street_edge_assignment_count WHERE street_edge_id = 27101;
