openapi: 3.0.3
info:
  title: Project Sidewalk API
  version: 1.0.1
  description: The current iteration of the Project Sidewalk API allows you to retrieve data that has been collected through Project Sidewalk, in addition to accessibility ratings based on this data.
  contact:
    name: Project Sidewalk
    email: sidewalk@cs.washington.edu
    url: https://sidewalk-newberg-test.cs.washington.edu
servers:
  - url: https://sidewalk-newberg-test.cs.washington.edu
    description: Test server for Newberg, Oregon
  - url: https://sidewalk-sea-test.cs.washington.edu
    description: Test server for Seattle, Washington
paths:
  /v2/overallStats:
    get:
      summary: Get overall stats
      description: Get a bunch of stats about this city's Project Sidewalk data.
      operationId: v2GetOverallStats
      parameters:
        - name: filterLowQuality
          in: query
          description: Optional parameter to remove low quality data
          required: false
          schema:
            type: boolean
            default: false
        - name: filetype
          in: query
          description: Optional parameter to choose output format; defaults to GeoJSON.
          required: false
          schema:
            type: string
            enum:
              - geojson
              - csv
              - shapefile
      responses:
        '200':
          description: Successful data retrieval!!
          content:
            application/json:
              examples:
                first-example:
                  summary: Example successful response
                  value:
                    km_explored: 38.436
                    user_counts:
                      all_users: 96
                      labelers: 48
  /v2/access/score/neighborhoods:
    get:
      summary: Get neighborhood Access Score
      description: Get Access Score for the neighborhoods that are fully within the given lat/lng bounds.
      operationId: v2AccessScoreNeighorhood
      parameters:
        - name: lat1
          in: query
          description: Latitude for first corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: 45.305
        - name: lng1
          in: query
          description: Longitude for first corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: -123.01
        - name: lat2
          in: query
          description: Latitude for second corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: 45.345
        - name: lng2
          in: query
          description: Longitude for second corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: -122.95
        - name: filetype
          in: query
          description: Optional parameter to choose output format; defaults to GeoJSON.
          required: false
          schema:
            type: string
            default: geojson
            enum:
              - geojson
              - csv
              - shapefile
            example: geojson
      responses:
        '200':
          description: Successful data retrieval
  /v2/access/attributes:
    get:
      summary: Get Accessibility Attribute Clusters
      description: Get accessibility attributes that are within the given lat/lng bounds. These attributes are created from clustering user's labels, so they should represent one distinct problem or feature per cluster.
      operationId: v2AccessAttributes
      parameters:
        - name: lat1
          in: query
          description: Latitude for first corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: 45.305
        - name: lng1
          in: query
          description: Longitude for first corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: -123.01
        - name: lat2
          in: query
          description: Latitude for second corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: 45.345
        - name: lng2
          in: query
          description: Longitude for second corner of a bounding box
          required: true
          schema:
            type: number
            format: double
            example: -122.95
        - name: severity
          in: query
          description: Filter for clusters with the given severity rating as a rounded mean of the labels' severity.
          required: false
          schema:
            type: string
            nullable: true
            enum:
              - none
              - '1'
              - '2'
              - '3'
              - '4'
              - '5'
        - name: filetype
          in: query
          description: Optional parameter to choose output format; defaults to GeoJSON.
          required: false
          schema:
            type: string
            default: geojson
            enum:
              - geojson
              - csv
              - shapefile
            example: geojson
      responses:
        '200':
          description: Successful data retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attribute'
components:
  schemas:
    Point:
      type: object
      description: GeoJSON point geometry
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - Point
          description: The geometry type
        coordinates:
          type: array
          description: A two item array showing [longitude, latitude] of the point.
          items:
            type: number
            format: double
          maxItems: 2
          minItems: 2
    Attribute:
      type: object
      description: GeoJSON Feature representing an accessibility attribute.
      required:
        - type
        - geometry
      properties:
        type:
          type: string
          enum:
            - Feature
        geometry:
          $ref: '#/components/schemas/Point'
        properties:
          type: object
          properties:
            cluster_id:
              type: integer
              format: int64
              description: A unique identifier for a cluster. This identifier is not guaranteed to persist over time.
            label_type:
              type: string
              description: The type of label that was placed.
              example: CurbRamp
              enum:
                - CurbRamp
                - NoCurbRamp
                - SurfaceProblem
                - Obstacle
                - NoSidewalk
                - Crosswalk
                - Signal
