* [32mdevelop[m
  [31mremotes/origin/1007-mturk-cluster-all-label-types[m
  [31mremotes/origin/1015-MTurk-irr-javascript[m
  [31mremotes/origin/1034-turk-completion[m
  [31mremotes/origin/1034-turk-stats[m
  [31mremotes/origin/1046-exclude-researcher-mturk-hits[m
  [31mremotes/origin/1059-accuracy-calculation[m
  [31mremotes/origin/1077-role-specific-survey-questions[m
  [31mremotes/origin/1144-choropleth-remove-redundant-code[m
  [31mremotes/origin/1158-complete-neighborhood-endless-loop[m
  [31mremotes/origin/1189-admin-distance-today-in-chart[m
  [31mremotes/origin/1190-logging-empty-pano-ids[m
  [31mremotes/origin/1244-improve-audit-time-queries[m
  [31mremotes/origin/1258-update-play-framework[m
  [31mremotes/origin/1269-ui-prompt-user-to-zoom-in-on-GSV-window[m
  [31mremotes/origin/1338-nextcity-improve-load-time[m
  [31mremotes/origin/1372-integrate-validation-missions[m
  [31mremotes/origin/1391-validation-view-underneath-labels[m
  [31mremotes/origin/1419-landing-page-for-mobile[m
  [31mremotes/origin/1452-labeling-guide-make-thumbnails-same-size[m
  [31mremotes/origin/1607-pop-up-text-left-aligned[m
  [31mremotes/origin/1626-new-city-pittsburgh[m
  [31mremotes/origin/1635-UI-more-completion-info-sidebar[m
  [31mremotes/origin/1680-give-users-more-feedback-on-dashboard[m
  [31mremotes/origin/1718-admin-playback-tool-broken[m
  [31mremotes/origin/1737-Show-Current-Labels-On-Return[m
  [31mremotes/origin/1782-feedback-when-no-imagery-on-admin-page[m
  [31mremotes/origin/1832-API-Create-ArcGIS-API[m
  [31mremotes/origin/1853-rapid-validate-overlay-buttons-onto-GSV-panos[m
  [31mremotes/origin/1888-validation-prioritize-using-cv[m
  [31mremotes/origin/1904-Mobile-Sign-In[m
  [31mremotes/origin/1904-Mobile-Sign-In-Page[m
  [31mremotes/origin/1904-Sign-In-Mobile[m
  [31mremotes/origin/1907-Sidewalk-Gallery[m
  [31mremotes/origin/2098-Single-Redirect-Sign-Up[m
  [31mremotes/origin/2098-bug-losing-user-authentication[m
  [31mremotes/origin/2124-admin-add-total-distance-audited[m
  [31mremotes/origin/2177-gamification-leaderboard[m
  [31mremotes/origin/2198-add-total-user-count-across-user-types-to-admin-dashboard[m
  [31mremotes/origin/2252-change-validation-sidebar-header-text-for-examples[m
  [31mremotes/origin/228-onboarding-walk-tutorial[m
  [31mremotes/origin/2281-add-badges-to-user-dashboard[m
  [31mremotes/origin/282-mobile-device-support[m
  [31mremotes/origin/282-mobiledevice-support-unfinished[m
  [31mremotes/origin/303-autoresize-auditpane[m
  [31mremotes/origin/342-admin-anonymous-retention-graph[m
  [31mremotes/origin/342-table-time-spent[m
  [31mremotes/origin/429-label-sticking-problem[m
  [31mremotes/origin/453-flashing-arrows[m
  [31mremotes/origin/496-user-starts-off-route[m
  [31mremotes/origin/593-move-to-docker[m
  [31mremotes/origin/610-ui-autofocus-login-email[m
  [31mremotes/origin/678-disable-zoom-plus-minus[m
  [31mremotes/origin/723-relaunch-beautify-choropleth[m
  [31mremotes/origin/816-b-navbar-menu-tab[m
  [31mremotes/origin/825-pop-ups-redesign[m
  [31mremotes/origin/837-admin-change-user-roles[m
  [31mremotes/origin/867-scroll-down-arrow-for-each-section[m
  [31mremotes/origin/877-cluster-on-server[m
  [31mremotes/origin/894-update-deploy-script[m
  [31mremotes/origin/909-improve-choropleth-loadtime[m
  [31mremotes/origin/911-facebook-link-metadata[m
  [31mremotes/origin/933-Mouseover-choropleth-regions-show-popup[m
  [31mremotes/origin/933-ui-choropleth-popup-1[m
  [31mremotes/origin/933-ui-choropleth-popup-2[m
  [31mremotes/origin/947-panorama-change-upload-data[m
  [31mremotes/origin/CSCW-map-visualizations[m
  [31mremotes/origin/CSCW-route-vis-newberg[m
  [31mremotes/origin/CSCW-route-visualization[m
  [31mremotes/origin/HEAD[m -> origin/develop
  [31mremotes/origin/admin-add-label-search[m
  [31mremotes/origin/admin-fix-panorama-label-location[m
  [31mremotes/origin/admin-label-search-v2[m
  [31mremotes/origin/admin-tabs-1[m
  [31mremotes/origin/alg-sidewalk-detect[m
  [31mremotes/origin/alg-sidewalk-detection[m
  [31mremotes/origin/assets-analytics2[m
  [31mremotes/origin/data-vis-tool[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/dockerize-app[m
  [31mremotes/origin/fixed-size-routes[m
  [31mremotes/origin/fog[m
  [31mremotes/origin/generate-map[m
  [31mremotes/origin/geotools-crs-error-fix[m
  [31mremotes/origin/ground-truth-lists-displaying[m
  [31mremotes/origin/groundtruth-add-admin-sign-in[m
  [31mremotes/origin/groundtruth-change-label-severity[m
  [31mremotes/origin/groundtruth-export-to-tables[m
  [31mremotes/origin/issues-on-production[m
  [31mremotes/origin/landing-page[m
  [31mremotes/origin/master[m
  [31mremotes/origin/merge-dev-into-mturk[m
  [31mremotes/origin/mt-analyze-turk-pilot-data[m
  [31mremotes/origin/pageDown[m
  [31mremotes/origin/release-notes-#354[m
  [31mremotes/origin/sidewalk-generated-routes-map[m
  [31mremotes/origin/sidewalk-mturk[m
  [31mremotes/origin/sidewalk-mturk-teja[m
  [31mremotes/origin/sidewalk-mturk-v2[m
  [31mremotes/origin/sidewalk-mturk-v2-add-manual-condition-assignment[m
  [31mremotes/origin/sidewalk-mturk-v2-add-route-visualization[m
  [31mremotes/origin/test-hit-approval[m
