package service

import models.utils.CommonUtils
import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers
import play.api.libs.json.{JsValue, Json}

import scala.io.Source

/**
 * Cross-implementation parity for the label lat/lng estimator (#5084): the Scala path must reproduce the reference
 * fixture that the JS path (test/js/latLngEstimationParity.test.js) is also held to. The SQL backfill (352.sql) was
 * checked against the same fixture once, by hand, during the sign-off; no test re-runs it. Of the two suites, this
 * one gates CI (the jest suite is advisory there).
 *
 * The fixture, `test/fixtures/latLngEstimationParity.json`, is generated by the label-latlng-estimation repo
 * (`python/run_signoff.py fixture`) from an independent port of the production formula on the 6371 km sphere, and
 * covers the seam, the bearing's 0/360 wrap, a negative unwrapped heading, the blend angle from both sides, the
 * horizon and above it (the bounded tail), the nadir, both hemispheres, and 48 random clicks over four pano
 * resolutions. Tolerances are the fixture's own: 1e-9 degrees, about a tenth of a millimetre on the ground.
 *
 * Regenerate the fixture whenever the constants in `PanoDataService.LatLngEstimation` change; a stale fixture fails
 * here rather than drifting.
 */
class LatLngEstimationParitySpec extends AnyFunSuite with Matchers {

  private lazy val fixture: JsValue = {
    val source = Source.fromFile("test/fixtures/latLngEstimationParity.json", "UTF-8")
    try Json.parse(source.mkString)
    finally source.close()
  }
  private lazy val cases: Seq[JsValue] = (fixture \ "cases").as[Seq[JsValue]]

  test("the fixture was generated for the constants this build ships") {
    (fixture \ "constants" \ "camera_height_m").as[Double] shouldBe PanoDataService.LatLngEstimation.CAMERA_HEIGHT_M
    (fixture \ "constants" \ "blend_deg").as[Double] shouldBe PanoDataService.LatLngEstimation.BLEND_DEG
    (fixture \ "constants" \ "max_distance_m").as[Double] shouldBe PanoDataService.LatLngEstimation.MAX_DISTANCE_M
    (fixture \ "constants" \ "earth_radius_m").as[Double] shouldBe CommonUtils.EARTH_RADIUS_KM * 1000.0
    cases.size should be >= 50
  }

  test("geodesy decision (#5084): the production sphere's radius is 6371.0 km") {
    // Sphere vs WGS84 displaces a label by at most 10.7 cm at the 23.85 m largest answer, 5.3 cm at the 11.8 m blend
    // distance and 2.2 cm at 5 m, all well under the estimator's 0.4 m median error, so the sphere stays and its
    // radius is pinned where the decision is greppable. 352.sql shares 6371.0 km; the client's turf (6371.0088 km)
    // is 1.4 ppm away, under 0.1 mm. An ellipsoid "upgrade" moves answers ~1e-6 deg, which the parity test catches.
    CommonUtils.EARTH_RADIUS_KM shouldBe 6371.0
  }

  test("every fixture case reproduces through calculatePovFromPanoXY, estimateDistanceFromPanoM and toLatLng") {
    val tolDeg   = (fixture \ "tolerance" \ "lat_lng_deg").as[Double]
    val tolAngle = (fixture \ "tolerance" \ "heading_deg").as[Double]
    val tolDist  = (fixture \ "tolerance" \ "distance_m").as[Double]
    cases.foreach { c =>
      val name          = (c \ "name").as[String]
      val panoLat       = (c \ "pano_lat").as[Double]
      val panoLng       = (c \ "pano_lng").as[Double]
      val panoX         = (c \ "pano_x").as[Int]
      val panoY         = (c \ "pano_y").as[Int]
      val width         = (c \ "pano_width").as[Int]
      val height        = (c \ "pano_height").as[Int]
      val cameraHeading = (c \ "camera_heading").as[Double]
      val expected      = c \ "expected"

      withClue(s"case '$name': ") {
        val pov = PanoDataService.calculatePovFromPanoXY(panoX, panoY, width, height, cameraHeading)
        // Circular difference: a bearing on the 0/360 wrap may come out as 359.999... on one side and 0 on the other.
        val headingGap = math.abs(pov.heading - (expected \ "heading_deg").as[Double]) % 360
        math.min(headingGap, 360 - headingGap) shouldBe (0.0 +- tolAngle)
        pov.pitch shouldBe ((expected \ "pitch_deg").as[Double] +- tolAngle)
        PanoDataService.estimateDistanceFromPanoM(-pov.pitch) shouldBe ((expected \ "distance_m").as[Double] +- tolDist)

        val (lat, lng) = PanoDataService.toLatLng(panoLat, panoLng, panoX, panoY, width, height, cameraHeading)
        lat shouldBe ((expected \ "lat").as[Double] +- tolDeg)
        lng shouldBe ((expected \ "lng").as[Double] +- tolDeg)
      }
    }
  }
}
