package service

import models.utils.CommonUtils
import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers
import play.api.libs.json.{JsValue, Json}

import scala.io.Source

/**
 * Cross-implementation parity for the label lat/lng estimator (#5084): the Scala path must reproduce the reference
 * fixture that the JS path (test/js/latLngEstimationParity.test.js) and the SQL backfill (352.sql) are held to.
 *
 * The fixture, `test/fixtures/latLngEstimationParity.json`, is generated by the label-latlng-estimation repo
 * (`python/run_signoff.py fixture`) from an independent port of the production formula on the 6371 km sphere, and
 * covers the seam, a negative unwrapped heading, the blend angle from both sides, the horizon and above it (the
 * bounded tail), the nadir, both hemispheres, and 48 random clicks over four pano resolutions. Tolerances are the
 * fixture's own: 1e-9 degrees, about a tenth of a millimetre on the ground.
 *
 * Regenerate the fixture whenever the constants in `PanoDataService.LatLngEstimation` change; a stale fixture fails
 * here rather than drifting.
 */
class LatLngEstimationParitySpec extends AnyFunSuite with Matchers {

  private lazy val fixture: JsValue = {
    val source = Source.fromFile("test/fixtures/latLngEstimationParity.json", "UTF-8")
    try Json.parse(source.mkString)
    finally source.close()
  }
  private lazy val cases: Seq[JsValue] = (fixture \ "cases").as[Seq[JsValue]]

  test("the fixture was generated for the constants this build ships") {
    (fixture \ "constants" \ "camera_height_m").as[Double] shouldBe PanoDataService.LatLngEstimation.CAMERA_HEIGHT_M
    (fixture \ "constants" \ "blend_deg").as[Double] shouldBe PanoDataService.LatLngEstimation.BLEND_DEG
    (fixture \ "constants" \ "max_distance_m").as[Double] shouldBe PanoDataService.LatLngEstimation.MAX_DISTANCE_M
    (fixture \ "constants" \ "earth_radius_m").as[Double] shouldBe CommonUtils.EARTH_RADIUS_KM * 1000.0
    cases.size should be >= 50
  }

  test("geodesy decision (#5084): destinations are spherical on the 6371 km mean radius") {
    // Sphere vs WGS84 ellipsoid displaces a label by at most ~11 cm at the estimator's 23.85 m largest answer and
    // ~2.5 cm at the median label distance, an order of magnitude under the estimator's own 0.4 m median error,
    // so the sphere is kept and its radius is pinned: the SQL backfill (352.sql) and this code share 6371.0 km,
    // and the Explore client's turf sphere (6371.0088 km) sits 1.4 ppm away, i.e. under 0.1 mm at any distance.
    CommonUtils.EARTH_RADIUS_KM shouldBe 6371.0
  }

  test("every fixture case reproduces through calculatePovFromPanoXY, estimateDistanceFromPanoM and toLatLng") {
    val tolDeg  = (fixture \ "tolerance" \ "lat_lng_deg").as[Double]
    val tolDist = (fixture \ "tolerance" \ "distance_m").as[Double]
    cases.foreach { c =>
      val name          = (c \ "name").as[String]
      val panoLat       = (c \ "pano_lat").as[Double]
      val panoLng       = (c \ "pano_lng").as[Double]
      val panoX         = (c \ "pano_x").as[Int]
      val panoY         = (c \ "pano_y").as[Int]
      val width         = (c \ "pano_width").as[Int]
      val height        = (c \ "pano_height").as[Int]
      val cameraHeading = (c \ "camera_heading").as[Double]
      val expected      = c \ "expected"

      withClue(s"case '$name': ") {
        val pov = PanoDataService.calculatePovFromPanoXY(panoX, panoY, width, height, cameraHeading)
        ((pov.heading % 360 + 360) % 360) shouldBe ((expected \ "heading_deg").as[Double] +- tolDeg)
        pov.pitch shouldBe ((expected \ "pitch_deg").as[Double] +- tolDeg)
        PanoDataService.estimateDistanceFromPanoM(-pov.pitch) shouldBe ((expected \ "distance_m").as[Double] +- tolDist)

        val (lat, lng) = PanoDataService.toLatLng(panoLat, panoLng, panoX, panoY, width, height, cameraHeading)
        lat shouldBe ((expected \ "lat").as[Double] +- tolDeg)
        lng shouldBe ((expected \ "lng").as[Double] +- tolDeg)
      }
    }
  }
}
