/**
 * Parity and behavior tests for AccessScoreModel (public/js/access-score/src/AccessScoreModel.js, #5217).
 *
 * The model re-runs the AccessScore engine in the browser so the tool can reweight scores without a server round
 * trip. It is held to the same fixture as the Scala engine, `test/fixtures/accessScoreParity.json` (generated by
 * `sbt "Test/runMain service.AccessScoreParityFixtureGen"`, pinned by test/service/AccessScoreParitySpec.scala):
 * every street case must reproduce the engine's `score` and `sub_scores` at the default weights, and its reweighted
 * results under each preset, to the fixture's tolerance. The rest pins what the sliders mean.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SRC = fs.readFileSync(path.join(REPO_ROOT, 'public/js/access-score/src/AccessScoreModel.js'), 'utf8');
const FIXTURE = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'test/fixtures/accessScoreParity.json'), 'utf8'));

/** A street feature in the API's shape, from a fixture case. */
function feature(c, i, extra = {}) {
    return {
        type: 'Feature',
        geometry: null,
        properties: {
            street_edge_id: i + 1,
            region_id: 1,
            audit_count: 1,
            length_meters: 100,
            severity_counts: c.severity_counts,
            tag_adjustments: c.tag_adjustments,
            cluster_counts: c.cluster_counts,
            ...extra,
        },
    };
}

const REGION = { region_id: 1, name: 'Fixture', rate: 1, total_distance_m: 6100, completed_distance_m: 6100 };

describe('AccessScoreModel', () => {
    let AccessScoreModel;
    const tol = FIXTURE.tolerance;
    const streets = { type: 'FeatureCollection', features: FIXTURE.streets.map((c, i) => feature(c, i)) };

    beforeAll(() => {
        window.eval(`${SRC}\nwindow.AccessScoreModel = AccessScoreModel;`);
        AccessScoreModel = window.AccessScoreModel;
    });

    test('the fixture carries the engine config and enough cases to mean something', () => {
        expect(FIXTURE.config.scored_types.length).toBe(7);
        expect(FIXTURE.streets.length).toBeGreaterThanOrEqual(50);
    });

    test('reproduces every fixture street at the default weights: score and per-type terms', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, [REGION]);
        expect(model.state.preset).toBe('default');
        FIXTURE.streets.forEach((c, i) => {
            const explained = model.explainStreet(i + 1);
            expect(Math.abs(explained.score - c.score)).toBeLessThan(tol);
            expect(Math.abs(model.streetScores[i] - c.score)).toBeLessThan(tol);
            for (const type of FIXTURE.config.scored_types) {
                expect(Math.abs(explained.terms[type].term - c.sub_scores[type])).toBeLessThan(tol);
            }
        });
    });

    test('reproduces every fixture street under each named preset', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, [REGION]);
        for (const preset of FIXTURE.config.preset_order.filter((id) => id !== 'default')) {
            model.setState({ preset });
            expect(model.state.preset).toBe(preset);
            FIXTURE.streets.forEach((c, i) => {
                const expected = c.reweighted.find((r) => r.preset === preset);
                const explained = model.explainStreet(i + 1);
                expect(Math.abs(explained.score - expected.score)).toBeLessThan(tol);
                for (const type of FIXTURE.config.scored_types) {
                    expect(Math.abs(explained.terms[type].term - expected.sub_scores[type])).toBeLessThan(tol);
                }
            });
        }
    });

    test('region roll-up matches the engine on the fixture region cases', () => {
        for (const r of FIXTURE.regions) {
            const pairs = r.streets.map((s) => [s.score, s.length_meters]);
            const live = AccessScoreModel.lengthWeightedMean(pairs);
            if (r.score === null) expect(live).toBeNull();
            else expect(Math.abs(live - r.score)).toBeLessThan(tol);
        }
    });

    test('a weights edit flips the preset to custom, and a matching edit flips it back', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, [REGION]);
        model.setState({ weights: { Obstacle: 1.7 } });
        expect(model.state.preset).toBe('custom');
        expect(model.signedWeight('Obstacle')).toBe(-1.7);
        model.setState({ weights: { Obstacle: 1.0 } });
        expect(model.state.preset).toBe('default');
    });

    test('all weights at zero leaves only tag adjustments; with tags off every audited street is the neutral 0.5', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, [REGION]);
        const zero = Object.fromEntries(FIXTURE.config.scored_types.map((t) => [t, 0]));
        model.setState({ weights: zero, tagsEnabled: false });
        for (let i = 0; i < model.streetCount; i++) expect(model.streetScores[i]).toBeCloseTo(0.5, 12);
    });

    test('severity emphasis 0 counts clusters regardless of rating', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, [REGION]);
        model.setState({ severityEmphasis: 0 });
        // "severity ladder": three obstacles rated 1, 2, 3 all count −1.0 each once ratings are ignored.
        const ladder = FIXTURE.streets.findIndex((c) => c.name === 'severity ladder');
        expect(model.explainStreet(ladder + 1).terms.Obstacle.term).toBeCloseTo(-3, 12);
        // "bad curb ramp flips negative" no longer flips: an un-rated curb ramp counts its full base.
        const bad = FIXTURE.streets.findIndex((c) => c.name === 'bad curb ramp flips negative');
        expect(model.explainStreet(bad + 1).terms.CurbRamp.term).toBeCloseTo(0.75, 12);
    });

    test('unaudited streets have no score and are left out of the histogram and the KPI mean', () => {
        const features = FIXTURE.streets.slice(0, 4).map((c, i) => feature(c, i, { audit_count: i === 0 ? 0 : 1 }));
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features }, [REGION]);
        expect(Number.isNaN(model.streetScores[0])).toBe(true);
        expect(model.explainStreet(1).score).toBeNull();
        const h = model.histogram();
        expect(h.total).toBeCloseTo(0.3, 12); // three audited 100 m streets, in km
        expect(model.kpis().auditedStreets).toBe(3);
    });

    test('regions: length-weighted vs mean roll-up, the completion floor, and the rankings', () => {
        const regions = [
            { region_id: 1, name: 'Whole', rate: 1, total_distance_m: 300, completed_distance_m: 300 },
            { region_id: 2, name: 'Thin', rate: 0.2, total_distance_m: 1000, completed_distance_m: 200 },
        ];
        const features = [
            feature(FIXTURE.streets[1], 0, { region_id: 1, length_meters: 100 }), // one good curb ramp
            feature(FIXTURE.streets[2], 1, { region_id: 1, length_meters: 300 }), // bad curb ramp
            feature(FIXTURE.streets[1], 2, { region_id: 2, length_meters: 50 }),
        ];
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features }, regions);
        const good = FIXTURE.streets[1].score;
        const bad = FIXTURE.streets[2].score;
        const [whole, thin] = model.regionStats;
        expect(whole.score).toBeCloseTo((good * 100 + bad * 300) / 400, 12);
        expect(whole.belowFloor).toBe(false);
        expect(thin.belowFloor).toBe(true);
        expect(model.ranked(5).top.map((r) => r.regionId)).toEqual([1]); // the thin region is floored out

        model.setState({ aggregation: 'mean' });
        expect(model.regionStats[0].score).toBeCloseTo((good + bad) / 2, 12);
        model.setState({ minCompletion: 0.1, unit: 'regions' });
        expect(model.regionStats[1].belowFloor).toBe(false);
        expect(model.histogram().total).toBe(2);
        expect(model.kpis().totalKm).toBeCloseTo(1.3, 12);
    });

    test('contributions report each type\'s mean term and mean cluster count over the scoped streets', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, [REGION]);
        const ids = new Set([2, 3]); // "one good curb ramp" and "bad curb ramp flips negative"
        const { means, clusterMeans, streets: n } = model.contributions({ streetIds: ids });
        expect(n).toBe(2);
        expect(clusterMeans.CurbRamp).toBe(1);
        expect(means.CurbRamp).toBeCloseTo((0.75 - 0.75) / 2, 12);
        expect(clusterMeans.Obstacle).toBe(0);
        const n2 = model.notable('streets', 3);
        expect(n2.hurt.type).toBe('CurbRamp');
        expect(n2.helped).toBeNull();
    });

    test('bins: binOf folds the top edge, streetBins tracks the scores, and the bin lookups honor a scope', () => {
        expect(AccessScoreModel.binOf(0)).toBe(0);
        expect(AccessScoreModel.binOf(0.4999)).toBe(9);
        expect(AccessScoreModel.binOf(0.5)).toBe(10);
        expect(AccessScoreModel.binOf(1)).toBe(19);
        const features = FIXTURE.streets.map((c, i) => feature(c, i, { audit_count: i === 0 ? 0 : 1 }));
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features }, [REGION]);
        expect(model.streetBins[0]).toBe(AccessScoreModel.UNBINNED);
        for (let i = 1; i < model.streetCount; i++) {
            expect(model.streetBins[i]).toBe(AccessScoreModel.binOf(model.streetScores[i]));
        }
        const good = model.streetIdsInBins(10, 20);
        model.streetIds.forEach((id, i) => {
            expect(good.has(id)).toBe(i > 0 && model.streetScores[i] >= 0.5);
        });
        expect(model.streetIdsInBins(0, 20, { streetIds: new Set([2, 3]) })).toEqual(new Set([2, 3]));
        expect(model.streetIdsInBins(0, 20).has(1)).toBe(false); // unaudited: in no bin
        expect(model.regionStreetIds(1).size).toBe(model.streetCount);
        // A weight change moves streets between bins, and the bins follow in the same pass.
        model.setState({ weights: { Obstacle: 0 } });
        for (let i = 1; i < model.streetCount; i++) {
            expect(model.streetBins[i]).toBe(AccessScoreModel.binOf(model.streetScores[i]));
        }
    });

    test('clusterBreakdown sums the cluster counts per type and bucket over the scoped streets', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, [REGION]);
        const all = model.clusterBreakdown();
        expect(all.streets).toBe(FIXTURE.streets.length);
        for (const entry of all.types) {
            for (const bucket of FIXTURE.config.severity_buckets) {
                const expected = FIXTURE.streets.reduce((n, c) => n + ((c.severity_counts[entry.type] || {})[bucket] || 0), 0);
                expect(entry.buckets[bucket]).toBe(expected);
            }
            expect(entry.total).toBe(Object.values(entry.buckets).reduce((a, b) => a + b, 0));
        }
        expect(all.total).toBe(all.types.reduce((n, t) => n + t.total, 0));
        const scoped = model.clusterBreakdown({ streetIds: new Set([2, 3]) }); // one curb ramp each
        expect(scoped.streets).toBe(2);
        expect(scoped.types.find((t) => t.type === 'CurbRamp').total).toBe(2);
        expect(scoped.types.find((t) => t.type === 'Obstacle').total).toBe(0);
    });

    test('kpis and the histogram take a scope, and rankedRegions orders every scored region', () => {
        const regions = [
            { region_id: 1, name: 'Whole', rate: 1, total_distance_m: 300, completed_distance_m: 300 },
            { region_id: 2, name: 'Good', rate: 1, total_distance_m: 100, completed_distance_m: 100 },
            { region_id: 3, name: 'Thin', rate: 0.2, total_distance_m: 1000, completed_distance_m: 200 },
        ];
        const features = [
            feature(FIXTURE.streets[1], 0, { region_id: 1, length_meters: 100 }), // one good curb ramp
            feature(FIXTURE.streets[2], 1, { region_id: 1, length_meters: 300 }), // bad curb ramp
            feature(FIXTURE.streets[1], 2, { region_id: 2, length_meters: 100 }),
            feature(FIXTURE.streets[1], 3, { region_id: 3, length_meters: 50, audit_count: 0 }),
        ];
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features }, regions);
        expect(model.rankedRegions().map((r) => r.regionId)).toEqual([2, 1]); // the thin region is floored out
        expect(model.ranked(1).top.map((r) => r.regionId)).toEqual([2]);
        expect(model.regionIdsInBins(0, 20)).toEqual(new Set([1, 2]));
        expect(model.regionIdsInBins(0, 20, { regionIds: new Set([2]) })).toEqual(new Set([2]));

        // Scoped KPIs count the streets given and measure their own lengths; unscoped ones use the region rows.
        const city = model.kpis();
        expect(city.streets).toBe(4);
        expect(city.totalKm).toBeCloseTo(1.4, 12);
        const scoped = model.kpis({ streetIds: new Set([1, 2]), regionIds: new Set([1]) });
        expect(scoped.streets).toBe(2);
        expect(scoped.auditedStreets).toBe(2);
        expect(scoped.totalKm).toBeCloseTo(0.4, 12);
        expect(scoped.auditedKm).toBeCloseTo(0.4, 12);
        expect(scoped.regions).toBe(1);
        expect(scoped.cityScore).toBeCloseTo(model.explainRegion(1).score, 12);

        model.setState({ unit: 'regions' });
        expect(model.histogram().total).toBe(2);
        expect(model.histogram({ regionIds: new Set([2]) }).total).toBe(1);
    });

    test('an empty city yields no NaN anywhere', () => {
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features: [] }, []);
        const k = model.kpis();
        expect(k.cityScore).toBeNull();
        expect(k.auditedKm).toBe(0);
        expect(model.histogram().total).toBe(0);
        expect(model.ranked().top).toEqual([]);
        expect(model.contributions().streets).toBe(0);
        expect(Object.values(model.contributions().clusterMeans).every((v) => v === 0)).toBe(true);
        expect(Object.values(model.contributions().means).every((v) => v === 0)).toBe(true);
    });
});
