/**
 * Parity and behavior tests for AccessScoreModel (public/js/access-score/src/AccessScoreModel.js, #5217).
 *
 * The model re-runs the AccessScore engine in the browser so the tool can reweight scores without a server round
 * trip. It is held to the same fixture as the Scala engine, `test/fixtures/accessScoreParity.json` (generated by
 * `sbt "Test/runMain service.AccessScoreParityFixtureGen"`, pinned by test/service/AccessScoreParitySpec.scala):
 * every street and intersection case must reproduce the engine's `score` and `sub_scores` at the default weights,
 * and its reweighted results under each of its reweightings, to the fixture's tolerance; the headline cases pin
 * how the two combine. The rest pins what the sliders mean.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SRC = fs.readFileSync(path.join(REPO_ROOT, 'public/js/access-score/src/AccessScoreModel.js'), 'utf8');
const FIXTURE = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'test/fixtures/accessScoreParity.json'), 'utf8'));

/** A street feature in the API's shape, from a fixture case. */
function feature(c, i, extra = {}) {
    return {
        type: 'Feature',
        geometry: null,
        properties: {
            street_edge_id: i + 1,
            region_id: 1,
            audit_count: 1,
            length_meters: c.length_meters ?? 100,
            severity_counts: c.severity_counts,
            tag_adjustments: c.tag_adjustments,
            cluster_counts: c.cluster_counts,
            ...extra,
        },
    };
}

const REGION = { region_id: 1, name: 'Fixture', rate: 1, total_distance_m: 6100, completed_distance_m: 6100 };
const NO_INTERSECTIONS = { type: 'FeatureCollection', features: [] };

/** An intersection feature in the API's shape, from a fixture case. */
function intersectionFeature(c, id, extra = {}) {
    return {
        type: 'Feature',
        geometry: null,
        properties: {
            intersection_id: id,
            region_id: 1,
            degree: 4,
            grade_separated: false,
            street_edge_ids: [],
            audit_count: 1,
            severity_counts: c.severity_counts,
            tag_adjustments: c.tag_adjustments,
            cluster_counts: c.cluster_counts,
            ...extra,
        },
    };
}

describe('AccessScoreModel', () => {
    let AccessScoreModel;
    const tol = FIXTURE.tolerance;
    const streets = { type: 'FeatureCollection', features: FIXTURE.streets.map((c, i) => feature(c, i)) };

    beforeAll(() => {
        window.eval(`${SRC}\nwindow.AccessScoreModel = AccessScoreModel;`);
        AccessScoreModel = window.AccessScoreModel;
    });

    test('the fixture carries the engine config and enough cases to mean something', () => {
        expect(FIXTURE.config.scored_types.length).toBe(7);
        expect(FIXTURE.streets.length).toBeGreaterThanOrEqual(50);
    });

    test('reproduces every fixture street at the default weights: score and per-type terms', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, NO_INTERSECTIONS, [REGION]);
        expect(model.weightsAreDefault).toBe(true);
        FIXTURE.streets.forEach((c, i) => {
            const explained = model.explainStreet(i + 1);
            expect(Math.abs(explained.score - c.score)).toBeLessThan(tol);
            expect(Math.abs(model.streetScores[i] - c.score)).toBeLessThan(tol);
            for (const type of FIXTURE.config.scored_types) {
                expect(Math.abs(explained.terms[type].term - c.sub_scores[type])).toBeLessThan(tol);
            }
        });
    });

    test('reproduces every fixture street under each reweighting the fixture carries', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, NO_INTERSECTIONS, [REGION]);
        for (const preset of FIXTURE.config.preset_order.filter((id) => id !== 'default')) {
            model.setState({ weights: { ...FIXTURE.config.presets[preset] } });
            expect(model.weightsAreDefault).toBe(false);
            FIXTURE.streets.forEach((c, i) => {
                const expected = c.reweighted.find((r) => r.preset === preset);
                const explained = model.explainStreet(i + 1);
                expect(Math.abs(explained.score - expected.score)).toBeLessThan(tol);
                for (const type of FIXTURE.config.scored_types) {
                    expect(Math.abs(explained.terms[type].term - expected.sub_scores[type])).toBeLessThan(tol);
                }
            });
        }
    });

    test('length normalization: a problem is a density per 100 m, floored at 25 m, and only for the marked types', () => {
        const lengths = [10, 25, 50, 100, 400];
        const obstacle = FIXTURE.streets.find((c) => c.cluster_counts.Obstacle === 1 && c.cluster_counts.SurfaceProblem === 0
            && c.cluster_counts.CurbRamp === 0);
        const ramp = FIXTURE.streets.find((c) => c.cluster_counts.CurbRamp === 1 && c.cluster_counts.Obstacle === 0);
        const features = lengths.flatMap((length, k) => [
            feature(obstacle, 2 * k, { length_meters: length }),
            feature(ramp, 2 * k + 1, { length_meters: length }),
        ]);
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features },
            NO_INTERSECTIONS, [REGION]);
        const { per_meters: per, min_length_meters: min } = FIXTURE.config.length_normalization;
        const at100 = model.explainStreet(2 * lengths.indexOf(100) + 1).terms.Obstacle;
        lengths.forEach((length, k) => {
            const o = model.explainStreet(2 * k + 1).terms.Obstacle;
            expect(o.lengthFactor).toBeCloseTo(per / Math.max(length, min), 12);
            expect(o.term).toBeCloseTo(at100.term * o.lengthFactor, 12);
            const r = model.explainStreet(2 * k + 2).terms.CurbRamp;
            expect(r.lengthFactor).toBe(1);
            expect(r.term).toBeCloseTo(model.explainStreet(2 * lengths.indexOf(100) + 2).terms.CurbRamp.term, 12);
        });
        // An engine that publishes no normalization block scales nothing.
        const older = { ...FIXTURE.config };
        delete older.length_normalization;
        const legacy = new AccessScoreModel(older, { type: 'FeatureCollection', features }, NO_INTERSECTIONS, [REGION]);
        expect(legacy.explainStreet(1).terms.Obstacle.lengthFactor).toBe(1);
    });

    test('region roll-up matches the engine on the fixture region cases', () => {
        for (const r of FIXTURE.regions) {
            const pairs = r.streets.map((s) => [s.score, s.length_meters]);
            const live = AccessScoreModel.lengthWeightedMean(pairs);
            if (r.score === null) expect(live).toBeNull();
            else expect(Math.abs(live - r.score)).toBeLessThan(tol);
        }
    });

    test('reproduces every fixture intersection at the default weights and under each reweighting', () => {
        const features = FIXTURE.intersections.map((c, j) => intersectionFeature(c, j + 1));
        const model = new AccessScoreModel(FIXTURE.config, NO_INTERSECTIONS, { type: 'FeatureCollection', features },
            [REGION]);
        expect(model.intersectionCount).toBe(FIXTURE.intersections.length);
        const check = (expectedOf) => FIXTURE.intersections.forEach((c, j) => {
            const expected = expectedOf(c);
            const explained = model.explainIntersection(j + 1);
            expect(Math.abs(explained.score - expected.score)).toBeLessThan(tol);
            for (const type of FIXTURE.config.intersection_types) {
                expect(Math.abs(explained.terms[type].term - expected.sub_scores[type])).toBeLessThan(tol);
            }
            // The along-length types never score a crossing, whatever the fixture's zero columns say.
            expect(Object.keys(explained.terms).sort()).toEqual([...FIXTURE.config.intersection_types].sort());
        });
        check((c) => c);
        for (const preset of FIXTURE.config.preset_order.filter((id) => id !== 'default')) {
            model.setState({ weights: { ...FIXTURE.config.presets[preset] } });
            check((c) => c.reweighted.find((r) => r.preset === preset));
        }
    });

    test('headline: the plain mean of the segment and whichever end crossings carry a score', () => {
        for (const h of FIXTURE.headlines) {
            const live = AccessScoreModel.headline(h.segment_score, h.end_scores);
            if (h.score === null) expect(live).toBeNull();
            else expect(Math.abs(live - h.score)).toBeLessThan(tol);
        }
    });

    test('a street is colored by its headline: segment plus the scored crossings at its ends', () => {
        const ramps = FIXTURE.intersections.find((c) => c.name === 'four good ramps');
        const missing = FIXTURE.intersections.find((c) => c.name === 'missing ramp, no alternate');
        const intersections = { type: 'FeatureCollection', features: [
            intersectionFeature(ramps, 10),
            intersectionFeature(missing, 11),
            intersectionFeature(ramps, 12, { grade_separated: true }),
            intersectionFeature(ramps, 13, { audit_count: 0 }),
        ] };
        const seg = FIXTURE.streets[0];
        const features = [
            feature(seg, 0, { start_intersection_id: 10, end_intersection_id: 11 }), // both ends scored
            feature(seg, 1, { start_intersection_id: 12, end_intersection_id: 11 }), // one end grade-separated
            feature(seg, 2, { start_intersection_id: null, end_intersection_id: 13 }), // dead end + unaudited end
            feature(seg, 3, { start_intersection_id: 10, end_intersection_id: 11, audit_count: 0 }),
            feature(seg, 4, { start_intersection_id: 999 }), // an end the feed does not know
        ];
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features }, intersections,
            [REGION]);
        const s1 = model.explainStreet(1);
        expect(s1.segmentScore).toBeCloseTo(seg.score, 12);
        expect(s1.startIntersection).toEqual({ id: 10, score: expect.any(Number) });
        expect(Math.abs(s1.startIntersection.score - ramps.score)).toBeLessThan(tol);
        expect(Math.abs(s1.endIntersection.score - missing.score)).toBeLessThan(tol);
        expect(s1.score).toBeCloseTo((seg.score + ramps.score + missing.score) / 3, 12);
        expect(model.streetScores[0]).toBeCloseTo(s1.score, 12);
        expect(model.streetBins[0]).toBe(AccessScoreModel.binOf(s1.score));

        const s2 = model.explainStreet(2);
        expect(s2.startIntersection).toEqual({ id: 12, score: null });
        expect(model.explainIntersection(12).gradeSeparated).toBe(true);
        expect(s2.score).toBeCloseTo((seg.score + missing.score) / 2, 12);

        const s3 = model.explainStreet(3);
        expect(s3.startIntersection).toBeNull();
        expect(s3.endIntersection).toEqual({ id: 13, score: null });
        expect(model.explainIntersection(13).audited).toBe(false);
        expect(s3.score).toBeCloseTo(seg.score, 12);

        // Unaudited stays unscored even between two scored crossings: nobody has looked at the block.
        const s4 = model.explainStreet(4);
        expect(s4.score).toBeNull();
        expect(s4.segmentScore).toBeNull();
        expect(s4.startIntersection.score).not.toBeNull();
        expect(Number.isNaN(model.streetScores[3])).toBe(true);

        expect(model.explainStreet(5).startIntersection).toBeNull();
        expect(model.explainStreet(5).score).toBeCloseTo(seg.score, 12);

        // A reweighting moves the crossings and the headline together.
        model.setState({ weights: { CurbRamp: 0 } });
        const after = model.explainStreet(1);
        expect(after.startIntersection.score).toBeCloseTo(0.5, 12);
        expect(after.score).toBeCloseTo((after.segmentScore + 0.5 + after.endIntersection.score) / 3, 12);
        // Region roll-up follows the headline, length-weighted.
        const region = model.explainRegion(1);
        const audited = [1, 2, 3, 5].map((id) => model.explainStreet(id));
        const pairs = audited.map((st) => [st.score, st.lengthM]);
        expect(region.score).toBeCloseTo(AccessScoreModel.lengthWeightedMean(pairs), 12);
    });

    test('a weights edit makes the weights custom, and a matching edit makes them default again', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, NO_INTERSECTIONS, [REGION]);
        model.setState({ weights: { Obstacle: 1.7 } });
        expect(model.weightsAreDefault).toBe(false);
        expect(model.signedWeight('Obstacle')).toBe(-1.7);
        model.setState({ weights: { Obstacle: 1.0 } });
        expect(model.weightsAreDefault).toBe(true);
    });

    test('all weights at zero leaves only the tag adjustments, which always apply', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, NO_INTERSECTIONS, [REGION]);
        const zero = Object.fromEntries(FIXTURE.config.scored_types.map((t) => [t, 0]));
        model.setState({ weights: zero });
        FIXTURE.streets.forEach((c, i) => {
            const explained = model.explainStreet(i + 1);
            const tagsOnly = FIXTURE.config.scored_types.reduce((sum, type) => sum + explained.terms[type].term, 0);
            expect(explained.preSigmoid).toBeCloseTo(tagsOnly, 12);
            for (const type of FIXTURE.config.scored_types) expect(explained.terms[type].weighted).toBeCloseTo(0, 12);
        });
    });

    test('unaudited streets have no score and are left out of the histogram and the KPI mean', () => {
        const features = FIXTURE.streets.slice(0, 4).map((c, i) => feature(c, i, { audit_count: i === 0 ? 0 : 1 }));
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features },
            NO_INTERSECTIONS, [REGION]);
        expect(Number.isNaN(model.streetScores[0])).toBe(true);
        expect(model.explainStreet(1).score).toBeNull();
        const h = model.histogram();
        expect(h.total).toBeCloseTo(0.3, 12); // three audited 100 m streets, in km
        expect(model.kpis().auditedStreets).toBe(3);
    });

    test('regions: the length-weighted roll-up, the completion floor, and the rankings', () => {
        const regions = [
            { region_id: 1, name: 'Whole', rate: 1, total_distance_m: 300, completed_distance_m: 300 },
            { region_id: 2, name: 'Thin', rate: 0.2, total_distance_m: 1000, completed_distance_m: 200 },
        ];
        const features = [
            feature(FIXTURE.streets[1], 0, { region_id: 1, length_meters: 100 }), // one good curb ramp
            feature(FIXTURE.streets[2], 1, { region_id: 1, length_meters: 300 }), // bad curb ramp
            feature(FIXTURE.streets[1], 2, { region_id: 2, length_meters: 50 }),
        ];
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features },
            NO_INTERSECTIONS, regions);
        const good = FIXTURE.streets[1].score;
        const bad = FIXTURE.streets[2].score;
        const [whole, thin] = model.regionStats;
        expect(whole.score).toBeCloseTo((good * 100 + bad * 300) / 400, 12);
        expect(whole.belowFloor).toBe(false);
        expect(thin.belowFloor).toBe(true);
        expect(model.ranked(5).top.map((r) => r.regionId)).toEqual([1]); // the thin region is floored out

        model.setState({ unit: 'regions' });
        expect(model.histogram().total).toBe(1);
        expect(model.kpis().totalKm).toBeCloseTo(1.3, 12);
    });

    test('the completion floor is judged on the rounded percent the page prints', () => {
        const regions = [
            { region_id: 1, name: 'Just under', rate: 0.4996, total_distance_m: 1000, completed_distance_m: 499.6 },
            { region_id: 2, name: 'Just over', rate: 0.4949, total_distance_m: 1000, completed_distance_m: 494.9 },
        ];
        const features = [
            feature(FIXTURE.streets[1], 0, { region_id: 1 }),
            feature(FIXTURE.streets[1], 1, { region_id: 2 }),
        ];
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features },
            NO_INTERSECTIONS, regions);
        expect(AccessScoreModel.MIN_COMPLETION).toBe(0.5);
        expect(model.regionStats[0].belowFloor).toBe(false); // prints as 50%, so it counts as 50%
        expect(model.regionStats[1].belowFloor).toBe(true); // prints as 49%
    });

    test('contributions report each type\'s mean term and mean cluster count over the scoped streets', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, NO_INTERSECTIONS, [REGION]);
        const ids = new Set([2, 3]); // "one good curb ramp" and "bad curb ramp flips negative"
        const { means, clusterMeans, streets: n } = model.contributions({ streetIds: ids });
        expect(n).toBe(2);
        expect(clusterMeans.CurbRamp).toBe(1);
        expect(means.CurbRamp).toBeCloseTo((0.75 - 0.75) / 2, 12);
        expect(clusterMeans.Obstacle).toBe(0);
        const n2 = model.notable('streets', 3);
        expect(n2.hurt.type).toBe('CurbRamp');
        expect(n2.helped).toBeNull();
    });

    test('bins: binOf folds the top edge, streetBins tracks the scores, and the bin lookups honor a scope', () => {
        expect(AccessScoreModel.binOf(0)).toBe(0);
        expect(AccessScoreModel.binOf(0.4999)).toBe(4);
        expect(AccessScoreModel.binOf(0.5)).toBe(5);
        expect(AccessScoreModel.binOf(1)).toBe(9);
        const features = FIXTURE.streets.map((c, i) => feature(c, i, { audit_count: i === 0 ? 0 : 1 }));
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features },
            NO_INTERSECTIONS, [REGION]);
        expect(model.streetBins[0]).toBe(AccessScoreModel.UNBINNED);
        for (let i = 1; i < model.streetCount; i++) {
            expect(model.streetBins[i]).toBe(AccessScoreModel.binOf(model.streetScores[i]));
        }
        const good = model.streetIdsInBins(5, 10);
        model.streetIds.forEach((id, i) => {
            expect(good.has(id)).toBe(i > 0 && model.streetScores[i] >= 0.5);
        });
        expect(model.streetIdsInBins(0, 10, { streetIds: new Set([2, 3]) })).toEqual(new Set([2, 3]));
        expect(model.streetIdsInBins(0, 10).has(1)).toBe(false); // unaudited: in no bin
        expect(model.regionStreetIds(1).size).toBe(model.streetCount);
        expect(model.streetIdsInRegions([1])).toEqual(model.regionStreetIds(1));
        expect(model.streetIdsInRegions(new Set([99]))).toEqual(new Set());
        // Lengths sum by id, unknown ids counting nothing.
        const two = new Set([1, 2, 999]);
        expect(model.totalLengthM(two)).toBe(model.explainStreet(1).lengthM + model.explainStreet(2).lengthM);
        // A weight change moves streets between bins, and the bins follow in the same pass.
        model.setState({ weights: { Obstacle: 0 } });
        for (let i = 1; i < model.streetCount; i++) {
            expect(model.streetBins[i]).toBe(AccessScoreModel.binOf(model.streetScores[i]));
        }
    });

    test('clusterBreakdown sums the cluster counts per type and bucket over the scoped streets', () => {
        const model = new AccessScoreModel(FIXTURE.config, streets, NO_INTERSECTIONS, [REGION]);
        const all = model.clusterBreakdown();
        expect(all.streets).toBe(FIXTURE.streets.length);
        for (const entry of all.types) {
            for (const bucket of FIXTURE.config.severity_buckets) {
                const expected = FIXTURE.streets.reduce((n, c) => n + ((c.severity_counts[entry.type] || {})[bucket] || 0), 0);
                expect(entry.buckets[bucket]).toBe(expected);
            }
            expect(entry.total).toBe(Object.values(entry.buckets).reduce((a, b) => a + b, 0));
        }
        expect(all.total).toBe(all.types.reduce((n, t) => n + t.total, 0));
        const scoped = model.clusterBreakdown({ streetIds: new Set([2, 3]) }); // one curb ramp each
        expect(scoped.streets).toBe(2);
        expect(scoped.types.find((t) => t.type === 'CurbRamp').total).toBe(2);
        expect(scoped.types.find((t) => t.type === 'Obstacle').total).toBe(0);
    });

    test('clusterBreakdown pools the intersections at the scoped streets\' ends, each counted once', () => {
        const seg = FIXTURE.streets[0];
        const ramps = FIXTURE.intersections.find((c) => c.cluster_counts.CurbRamp > 0);
        const intersections = { type: 'FeatureCollection', features: [
            intersectionFeature(ramps, 10, { region_id: 1 }),
            intersectionFeature(ramps, 11, { region_id: 2 }),
        ] };
        const features = [
            feature(seg, 0, { region_id: 1, start_intersection_id: 10, end_intersection_id: 11 }),
            feature(seg, 1, { region_id: 1, start_intersection_id: 10, end_intersection_id: null }),
            feature(seg, 2, { region_id: 2, start_intersection_id: 11, end_intersection_id: null }),
        ];
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features }, intersections, [
            { region_id: 1, name: 'A', rate: 1, total_distance_m: 200, completed_distance_m: 200 },
            { region_id: 2, name: 'B', rate: 1, total_distance_m: 100, completed_distance_m: 100 },
        ]);
        const onStreet = seg.cluster_counts.CurbRamp || 0;
        const atCorner = ramps.cluster_counts.CurbRamp;
        const ramp = (b) => b.types.find((t) => t.type === 'CurbRamp').total;
        // A street's scope carries the ramps at both of its ends.
        const one = model.clusterBreakdown({ streetIds: new Set([1]) });
        expect(one.intersections).toBe(2);
        expect(ramp(one)).toBe(onStreet + 2 * atCorner);
        // Two streets sharing intersection 10 count it once.
        const two = model.clusterBreakdown({ streetIds: new Set([1, 2]) });
        expect(two.intersections).toBe(2);
        expect(ramp(two)).toBe(2 * onStreet + 2 * atCorner);
        // A region's scope takes the intersections of that region, whichever streets meet there.
        const region = model.clusterBreakdown({ regionIds: new Set([2]) });
        expect(region.streets).toBe(1);
        expect(region.intersections).toBe(1);
        expect(ramp(region)).toBe(onStreet + atCorner);
        // The city takes everything.
        const city = model.clusterBreakdown();
        expect(city.intersections).toBe(2);
        expect(ramp(city)).toBe(3 * onStreet + 2 * atCorner);
        expect(model.streetEndIntersectionIds(new Set([1, 2]))).toEqual(new Set([10, 11]));
        expect(model.regionIntersectionIds(2)).toEqual(new Set([11]));

        // The contribution means and the problem-cluster KPI pool the same crossings, so a corner type's effect
        // reaches the sidebar bars, the neighborhood popup, and the KPI strip rather than reading as ~0.
        const cornerTerm = model.explainIntersection(10).terms.CurbRamp.term;
        const segmentTerm = model.explainStreet(1).terms.CurbRamp.term;
        expect(cornerTerm).not.toBe(0);
        const oneC = model.contributions({ streetIds: new Set([1]) });
        expect(oneC.intersections).toBe(2);
        expect(oneC.clusterMeans.CurbRamp).toBe(onStreet + 2 * atCorner);
        expect(oneC.means.CurbRamp).toBeCloseTo(segmentTerm + 2 * cornerTerm, 12);
        const regionC = model.contributions({ regionIds: new Set([2]) });
        expect(regionC.streets).toBe(1);
        expect(regionC.intersections).toBe(1);
        expect(regionC.means.CurbRamp).toBeCloseTo(segmentTerm + cornerTerm, 12);
        const cityC = model.contributions();
        expect(cityC.intersections).toBe(2);
        expect(cityC.means.CurbRamp).toBeCloseTo((3 * segmentTerm + 2 * cornerTerm) / 3, 12);
        // A region's standout compares its pooled per-street terms with the city's.
        expect(model.notable('regions', 2).helped.type).toBe('CurbRamp');
        // Missing curb ramps are problems; give intersection 11 some and the KPI counts them where they are.
        const noRamps = FIXTURE.intersections.find((c) => c.cluster_counts.NoCurbRamp > 0);
        const withProblems = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features }, {
            type: 'FeatureCollection',
            features: [intersectionFeature(ramps, 10, { region_id: 1 }), intersectionFeature(noRamps, 11, { region_id: 2 })],
        }, [{ region_id: 1, name: 'A', rate: 1 }, { region_id: 2, name: 'B', rate: 1 }]);
        // `model`'s crossings carry ramps only, so its counts are the streets' own problems: the baseline.
        const atCorner11 = noRamps.cluster_counts.NoCurbRamp;
        const onStreets = (m, scope) => m.kpis(scope).problemClusters;
        expect(onStreets(withProblems)).toBe(onStreets(model) + atCorner11);
        expect(onStreets(withProblems, { regionIds: new Set([1]) })).toBe(onStreets(model, { regionIds: new Set([1]) }));
        expect(onStreets(withProblems, { regionIds: new Set([2]) }))
            .toBe(onStreets(model, { regionIds: new Set([2]) }) + atCorner11);
        // A street's scope takes its own ends: street 2 ends at the ramps-only corner, street 3 at the other.
        expect(onStreets(withProblems, { streetIds: new Set([2]) })).toBe(onStreets(model, { streetIds: new Set([2]) }));
        expect(onStreets(withProblems, { streetIds: new Set([3]) }))
            .toBe(onStreets(model, { streetIds: new Set([3]) }) + atCorner11);
    });

    test('kpis and the histogram take a scope, and rankedRegions orders every scored region', () => {
        const regions = [
            { region_id: 1, name: 'Whole', rate: 1, total_distance_m: 300, completed_distance_m: 300 },
            { region_id: 2, name: 'Good', rate: 1, total_distance_m: 100, completed_distance_m: 100 },
            { region_id: 3, name: 'Thin', rate: 0.2, total_distance_m: 1000, completed_distance_m: 200 },
        ];
        const features = [
            feature(FIXTURE.streets[1], 0, { region_id: 1, length_meters: 100 }), // one good curb ramp
            feature(FIXTURE.streets[2], 1, { region_id: 1, length_meters: 300 }), // bad curb ramp
            feature(FIXTURE.streets[1], 2, { region_id: 2, length_meters: 100 }),
            feature(FIXTURE.streets[1], 3, { region_id: 3, length_meters: 50, audit_count: 0 }),
        ];
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features },
            NO_INTERSECTIONS, regions);
        expect(model.rankedRegions().map((r) => r.regionId)).toEqual([2, 1]); // the thin region is floored out
        expect(model.ranked(1).top.map((r) => r.regionId)).toEqual([2]);
        expect(model.regionIdsInBins(0, 10)).toEqual(new Set([1, 2]));
        expect(model.regionIdsInBins(0, 10, { regionIds: new Set([2]) })).toEqual(new Set([2]));

        // Scoped KPIs count the streets given and measure their own lengths; unscoped ones use the region rows.
        const city = model.kpis();
        expect(city.streets).toBe(4);
        expect(city.totalKm).toBeCloseTo(1.4, 12);
        const scoped = model.kpis({ streetIds: new Set([1, 2]), regionIds: new Set([1]) });
        expect(scoped.streets).toBe(2);
        expect(scoped.auditedStreets).toBe(2);
        expect(scoped.totalKm).toBeCloseTo(0.4, 12);
        expect(scoped.auditedKm).toBeCloseTo(0.4, 12);
        expect(scoped.regions).toBe(1);
        expect(scoped.cityScore).toBeCloseTo(model.explainRegion(1).score, 12);

        model.setState({ unit: 'regions' });
        expect(model.histogram().total).toBe(2);
        expect(model.histogram({ regionIds: new Set([2]) }).total).toBe(1);
    });

    test('an empty city yields no NaN anywhere', () => {
        const model = new AccessScoreModel(FIXTURE.config, { type: 'FeatureCollection', features: [] },
            NO_INTERSECTIONS, []);
        const k = model.kpis();
        expect(k.cityScore).toBeNull();
        expect(k.auditedKm).toBe(0);
        expect(model.histogram().total).toBe(0);
        expect(model.ranked().top).toEqual([]);
        expect(model.contributions().streets).toBe(0);
        expect(Object.values(model.contributions().clusterMeans).every((v) => v === 0)).toBe(true);
        expect(Object.values(model.contributions().means).every((v) => v === 0)).toBe(true);
    });
});
