/**
 * Cross-implementation parity for the client-side label lat/lng estimator (#5084).
 *
 * `Label#toLatLng` (public/js/explore/src/label/Label.js) must land on the same position as the server's
 * `PanoDataService.toLatLng` and the SQL backfill in 352.sql for the same label. All three are held to one fixture,
 * `test/fixtures/latLngEstimationParity.json`, generated by the label-latlng-estimation repo from an independent
 * port of the formula on the 6371 km sphere (`python/run_signoff.py fixture`); the Scala side of this contract is
 * test/service/LatLngEstimationParitySpec.scala.
 *
 * The client runs the real vendored turf for the destination step, so this also pins that turf's sphere
 * (6371.0088 km) is close enough to the app's 6371 km: the 1.4 ppm radius gap moves a label under a tenth of a
 * millimetre, far inside the 1e-8 degree (~1 mm) tolerance used here. The fixture's own 1e-9 degree tolerance is
 * what the Scala path is held to; the client tolerance is looser by exactly that radius gap.
 *
 * The client takes a POV rather than a pano pixel: the fixture's expected heading/pitch are what
 * `calculatePovFromPanoXY` produces for the pixel, so the test feeds those in and checks the distance and the
 * destination.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const LABEL_SRC = fs.readFileSync(path.join(REPO_ROOT, 'public/js/explore/src/label/Label.js'), 'utf8');
const FIXTURE = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'test/fixtures/latLngEstimationParity.json'), 'utf8'));
const CLIENT_TOL_DEG = 1e-8;

/** Loads a fresh Label class into the jsdom global scope (a class declaration is not a globalThis property). */
function loadLabel() {
    window.eval(`${LABEL_SRC}\nwindow.Label = Label;`);
    return window.Label;
}

describe('Label lat/lng estimation parity with the server and the SQL backfill (#5084)', () => {
    let Label;

    beforeEach(() => {
        Label = loadLabel();
        window.svl = {
            minimap: { getMap: () => null },
            latLngEstimation: {
                blendDeg: FIXTURE.constants.blend_deg,
                maxDistanceM: FIXTURE.constants.max_distance_m,
                cameraHeightM: FIXTURE.constants.camera_height_m,
            },
        };
        Label.createMinimapMarker = () => ({ addListener: () => {} });
        // The real vendored turf (UMD), not a stub: the destination step is part of what is being pinned.
        window.turf = require(path.join(REPO_ROOT, 'public/vendor/turf/turf-7.3.4.min.js'));
    });

    test('the fixture was generated for the constants this test injects', () => {
        expect(FIXTURE.constants.earth_radius_m).toBe(6371000);
        expect(FIXTURE.cases.length).toBeGreaterThanOrEqual(50);
    });

    test.each(FIXTURE.cases.map((c) => [c.name, c]))('%s', (name, c) => {
        const label = new Label({
            labelType: 'CurbRamp',
            temporaryLabelId: 1,
            panoXY: { x: c.pano_x, y: c.pano_y },
            povOfLabelIfCentered: { heading: c.expected.heading_deg, pitch: c.expected.pitch_deg, zoom: 1 },
            panoLat: c.pano_lat,
            panoLng: c.pano_lng,
        });
        const { lat, lng, latLngComputationMethod } = label.toLatLng();
        expect(latLngComputationMethod).toBe('approximation3');
        expect(Math.abs(lat - c.expected.lat)).toBeLessThan(CLIENT_TOL_DEG);
        expect(Math.abs(lng - c.expected.lng)).toBeLessThan(CLIENT_TOL_DEG);
    });
});
