/** Entry point for the AccessScore tool (bundled by rolldown.config.mjs). */
import { AccessScoreApp } from '../access-score/main.js';
import { viewerClassFor } from '../common/pano-viewer/viewerClassFor.js';

const data = document.getElementById('page-entry').dataset;
const src = data.imagerySource;
// Gets all translations before building the page.
window.appManager.ready(() => {
  AccessScoreApp.start({
    mapboxApiKey: data.mapboxApiKey,
    viewerType: viewerClassFor(src),
    imageryAccessToken: data.imageryAccessToken,
    // The view sends a username only for a real account; anonymous sessions have autogenerated ones.
    username: data.username || null,
  });
});
