/** Entry point for the AccessScore tool (bundled by rolldown.config.mjs). */
import { AccessScoreApp } from '../access-score/main.js';
import { GsvViewer } from '../common/pano-viewer/GsvViewer.js';
import { Infra3dViewer } from '../common/pano-viewer/Infra3dViewer.js';
import { MapillaryViewer } from '../common/pano-viewer/MapillaryViewer.js';

const data = document.getElementById('page-entry').dataset;
const src = data.imagerySource;
// Gets all translations before building the page.
window.appManager.ready(() => {
  AccessScoreApp.start({
    mapboxApiKey: data.mapboxApiKey,
    viewerType: src === 'mapillary' ? MapillaryViewer : src === 'infra3d' ? Infra3dViewer : GsvViewer,
    imageryAccessToken: data.imageryAccessToken,
    // The view sends a username only for a real account; anonymous sessions have autogenerated ones.
    username: data.username || null,
  });
});
