-- Patched mainline 179.sql (issue #4700), generated by gen-patches.sh: only the
-- old_label_metadata INSERT differs (see harness/gen-patches.sh for why).
-- Making a table to hold old sv_image_x/y and pano-specific data so that we can roll back if we find an issue.
CREATE TABLE old_label_metadata (
    label_id INTEGER NOT NULL,
    old_pano_x INT NOT NULL,
    old_pano_y INT NOT NULL,
    old_camera_heading DOUBLE PRECISION NOT NULL,
    old_camera_pitch DOUBLE PRECISION NOT NULL,
    old_pano_lat DOUBLE PRECISION,
    old_pano_lng DOUBLE PRECISION,
    FOREIGN KEY (label_id) REFERENCES label(label_id)
);

-- Store the old data. Every DC label predates the fix; prefer the TRUE pre-fix
-- coordinates DC's fork saved (parked in dc_old_label_metadata_backup by preclean).
INSERT INTO old_label_metadata (label_id, old_pano_x, old_pano_y, old_camera_heading, old_camera_pitch, old_pano_lat, old_pano_lng)
SELECT label.label_id,
       COALESCE(dc_old_label_metadata_backup.old_sv_image_x, label_point.sv_image_x),
       COALESCE(dc_old_label_metadata_backup.old_sv_image_y, label_point.sv_image_y),
       label.photographer_heading, label.photographer_pitch, label.panorama_lat, label.panorama_lng
FROM label
INNER JOIN label_point ON label.label_id = label_point.label_id
LEFT JOIN dc_old_label_metadata_backup ON label.label_id = dc_old_label_metadata_backup.label_id;

-- Add the pano-specific data to the gsv_data table. Use the most recent values from the label table for each.
ALTER TABLE gsv_data RENAME COLUMN image_width TO width;
ALTER TABLE gsv_data RENAME COLUMN image_height TO height;
ALTER TABLE gsv_data RENAME COLUMN image_date TO capture_date;
ALTER TABLE gsv_data
    ADD COLUMN camera_heading DOUBLE PRECISION,
    ADD COLUMN camera_pitch DOUBLE PRECISION,
    ADD COLUMN lat DOUBLE PRECISION,
    ADD COLUMN lng DOUBLE PRECISION;

UPDATE gsv_data
SET camera_heading = recent.photographer_heading,
    camera_pitch = recent.photographer_pitch,
    lat = panorama_lat,
    lng = panorama_lng
FROM (
         SELECT gsv_panorama_id,
                photographer_heading,
                photographer_pitch,
                panorama_lat,
                panorama_lng,
                row_number() OVER (PARTITION BY gsv_panorama_id ORDER BY time_created DESC)
         FROM label
         WHERE photographer_heading <> 'NaN' AND photographer_pitch <> 'NaN'
     ) recent
WHERE gsv_data.gsv_panorama_id = recent.gsv_panorama_id
  AND row_number = 1;

-- Now that they've been moved to gsv_data, remove the columns from the label table.
ALTER TABLE label
    DROP COLUMN photographer_heading,
    DROP COLUMN photographer_pitch,
    DROP COLUMN panorama_lat,
    DROP COLUMN panorama_lng;

-- Update the sv_image_x/y values in the database. The math is essentially calling this in UtilitiesPanomarker.js:
-- calculatePanoXYFromPov(calculatePovIfCentered({heading: heading, pitch: pitch, zoom: zoom}, canvas_x, canvas_y, 720, 480), camera_heading, width, height).
UPDATE label_point
SET sv_image_x = (width + ROUND(width * (((atan2((360 / tan(0.5 * (CASE WHEN zoom = 1 THEN 89.75 WHEN zoom = 2 THEN 53 ELSE 195.93 / 1.92^3 END) * PI() / 180))*cos((pitch * PI() / 180.0)) * sin((heading * PI() / 180.0)) + (canvas_x - 360) * SIGN(cos((pitch * PI() / 180.0))) * cos((heading * PI() / 180.0)) + (240 - canvas_y) * -sin((pitch * PI() / 180.0)) * sin((heading * PI() / 180.0)), (360 / tan(0.5 * (CASE WHEN zoom = 1 THEN 89.75 WHEN zoom = 2 THEN 53 ELSE 195.93 / 1.92^3 END) * PI() / 180)) * cos((pitch * PI() / 180.0)) * cos((heading * PI() / 180.0)) + (canvas_x - 360) * -SIGN(cos((pitch * PI() / 180.0))) * sin((heading * PI() / 180.0)) + (240 - canvas_y) * -sin((pitch * PI() / 180.0)) * cos((heading * PI() / 180.0))) * 180.0 / PI())::DECIMAL % 360 + 360)::DECIMAL % 360 - (camera_heading + 180)::DECIMAL % 360) / 360)) % width,
    sv_image_y = (height / 2) - ROUND((height / 2) * ((asin(((0.5 * 720 / tan(0.5 * (CASE WHEN zoom = 1 THEN 89.75 WHEN zoom = 2 THEN 53 ELSE 195.93 / 1.92^3 END)*PI()/180)) * sin((pitch * PI() / 180.0)) + (480 / 2 - canvas_y) * cos((pitch * PI() / 180.0))) / sqrt(((0.5 * 720 / tan(0.5 * (CASE WHEN zoom = 1 THEN 89.75 WHEN zoom = 2 THEN 53 ELSE 195.93 / 1.92^3 END)*PI()/180)) * cos((pitch * PI() / 180.0)) * sin((heading * PI() / 180.0)) + (canvas_x - 720 / 2) * SIGN(cos((pitch * PI() / 180.0))) * cos((heading * PI() / 180.0)) + (480 / 2 - canvas_y) * -sin((pitch * PI() / 180.0)) * sin((heading * PI() / 180.0)))^2 + ((0.5 * 720 / tan(0.5 * (CASE WHEN zoom = 1 THEN 89.75 WHEN zoom = 2 THEN 53 ELSE 195.93 / 1.92^3 END)*PI()/180)) * cos((pitch * PI() / 180.0)) * cos((heading * PI() / 180.0)) + (canvas_x - 720 / 2) * -SIGN(cos((pitch * PI() / 180.0))) * sin((heading * PI() / 180.0)) + (480 / 2 - canvas_y) * -sin((pitch * PI() / 180.0)) * cos((heading * PI() / 180.0)))^2 + ((0.5 * 720 / tan(0.5 * (CASE WHEN zoom = 1 THEN 89.75 WHEN zoom = 2 THEN 53 ELSE 195.93 / 1.92^3 END)*PI()/180)) * sin((pitch * PI() / 180.0)) + (480 / 2 - canvas_y) * cos((pitch * PI() / 180.0)))^ 2)) * 180.0 / PI()) / 90))
FROM label
INNER JOIN gsv_data ON label.gsv_panorama_id = gsv_data.gsv_panorama_id
WHERE label_point.label_id = label.label_id
    AND gsv_data.width IS NOT NULL
    AND gsv_data.height IS NOT NULL
    AND gsv_data.camera_heading <> 'NaN'
    AND gsv_data.camera_pitch <> 'NaN';

-- Some small updates to column names, etc.
ALTER TABLE gsv_data
    ALTER COLUMN last_viewed SET DEFAULT now(),
    ALTER COLUMN last_viewed SET NOT NULL;
ALTER TABLE label_point RENAME COLUMN sv_image_x to pano_x;
ALTER TABLE label_point RENAME COLUMN sv_image_y to pano_y;


