-- Patched mainline 26.sql (issue #4700), generated by gen-patches.sh: 'PST' -> 'US/Eastern'
-- (DC's server wrote Eastern wall times), and the mission block is dropped (patches/16.sql
-- created mission with TIMESTAMPTZ directly).
ALTER TABLE label
    ALTER COLUMN time_created TYPE TIMESTAMPTZ USING time_created AT TIME ZONE 'US/Eastern',
    ALTER COLUMN time_created SET DEFAULT now();

ALTER TABLE user_survey_text_submission
    ALTER COLUMN time_submitted TYPE TIMESTAMPTZ USING time_submitted AT TIME ZONE 'US/Eastern',
    ALTER COLUMN time_submitted SET DEFAULT now();

ALTER TABLE user_survey_option_submission
    ALTER COLUMN time_submitted TYPE TIMESTAMPTZ USING time_submitted AT TIME ZONE 'US/Eastern',
    ALTER COLUMN time_submitted SET DEFAULT now();

ALTER TABLE version
    ALTER COLUMN version_start_time TYPE TIMESTAMPTZ USING version_start_time AT TIME ZONE 'US/Eastern',
    ALTER COLUMN version_start_time SET DEFAULT now();

ALTER TABLE user_clustering_session
    ALTER COLUMN time_created TYPE TIMESTAMPTZ USING time_created AT TIME ZONE 'US/Eastern',
    ALTER COLUMN time_created SET DEFAULT now();

ALTER TABLE global_clustering_session
    ALTER COLUMN time_created TYPE TIMESTAMPTZ USING time_created AT TIME ZONE 'US/Eastern',
    ALTER COLUMN time_created SET DEFAULT now();


