-- Patched mainline 26.sql (issue #4700), generated by gen-patches.sh: the naive columns are US/Eastern
-- before 2018-08-25 and UTC after (DC's server moved zones in Aug 2018; see gen-patches.sh), and the
-- mission block is dropped (patches/16.sql created mission with TIMESTAMPTZ directly).
ALTER TABLE label
    ALTER COLUMN time_created TYPE TIMESTAMPTZ USING CASE WHEN time_created < '2018-08-25' THEN time_created AT TIME ZONE 'US/Eastern' ELSE time_created AT TIME ZONE 'UTC' END,
    ALTER COLUMN time_created SET DEFAULT now();

ALTER TABLE user_survey_text_submission
    ALTER COLUMN time_submitted TYPE TIMESTAMPTZ USING CASE WHEN time_submitted < '2018-08-25' THEN time_submitted AT TIME ZONE 'US/Eastern' ELSE time_submitted AT TIME ZONE 'UTC' END,
    ALTER COLUMN time_submitted SET DEFAULT now();

ALTER TABLE user_survey_option_submission
    ALTER COLUMN time_submitted TYPE TIMESTAMPTZ USING CASE WHEN time_submitted < '2018-08-25' THEN time_submitted AT TIME ZONE 'US/Eastern' ELSE time_submitted AT TIME ZONE 'UTC' END,
    ALTER COLUMN time_submitted SET DEFAULT now();

ALTER TABLE version
    ALTER COLUMN version_start_time TYPE TIMESTAMPTZ USING CASE WHEN version_start_time < '2018-08-25' THEN version_start_time AT TIME ZONE 'US/Eastern' ELSE version_start_time AT TIME ZONE 'UTC' END,
    ALTER COLUMN version_start_time SET DEFAULT now();

ALTER TABLE user_clustering_session
    ALTER COLUMN time_created TYPE TIMESTAMPTZ USING CASE WHEN time_created < '2018-08-25' THEN time_created AT TIME ZONE 'US/Eastern' ELSE time_created AT TIME ZONE 'UTC' END,
    ALTER COLUMN time_created SET DEFAULT now();

ALTER TABLE global_clustering_session
    ALTER COLUMN time_created TYPE TIMESTAMPTZ USING CASE WHEN time_created < '2018-08-25' THEN time_created AT TIME ZONE 'US/Eastern' ELSE time_created AT TIME ZONE 'UTC' END,
    ALTER COLUMN time_created SET DEFAULT now();


