#!/usr/bin/env bash
# Generates the patches that are mechanical edits of repo evolutions (issue #4700), so the bulk of
# their SQL provably matches the mainline files rather than a hand transcription.
set -euo pipefail
HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
EVODIR=$(cd "$HERE/../../.." && pwd)/conf/evolutions/default
PATCHES=$HERE/../patches

ups() { awk '/^# --- !Ups/{flag=1;next} /^# --- !Downs/{flag=0} flag' "$EVODIR/$1.sql" | sed 's/;;/;/g'; }

# --- 26: TIMESTAMP -> TIMESTAMPTZ conversions. DC's naive timestamps are US/Eastern wall time until the server
# --- move in Aug 2018 and UTC afterwards (measured against the interaction log: labels dated <= 2018-08-21 sit
# --- 4-5 h ahead of their UTC FinishLabeling event, labels dated >= 2018-08-29 sit exactly on it). Also
# --- patches/16.sql already created mission with TIMESTAMPTZ, so its block is dropped.
{
  echo "-- Patched mainline 26.sql (issue #4700), generated by gen-patches.sh: the naive columns are US/Eastern"
  echo "-- before 2018-08-25 and UTC after (DC's server moved zones in Aug 2018; see gen-patches.sh), and the"
  echo "-- mission block is dropped (patches/16.sql created mission with TIMESTAMPTZ directly)."
  ups 26 | sed -E "s/USING ([a-z_]+) AT TIME ZONE 'PST'/USING CASE WHEN \\1 < '2018-08-25' THEN \\1 AT TIME ZONE 'US\\/Eastern' ELSE \\1 AT TIME ZONE 'UTC' END/" \
         | awk '/^ALTER TABLE mission$/{skip=1} skip && /mission_end SET DEFAULT now\(\);$/{skip=0;next} !skip'
} > "$PATCHES/26.sql"

# --- 179: the CV coordinate fix DC's fork partially backported (its evo 17). Everything verbatim
# --- except the old_label_metadata INSERT: the mainline version gate ('7.12.2') is meaningless for
# --- DC, and DC's fork saved the TRUE pre-fix coordinates, which preclean parked in
# --- dc_old_label_metadata_backup. The recompute UPDATE stays verbatim: it requires
# --- gsv_data.width IS NOT NULL, which is never true for DC (its fork nulled all dimensions), so
# --- it provably no-ops instead of double-transforming the already-fixed coordinates.
{
  echo "-- Patched mainline 179.sql (issue #4700), generated by gen-patches.sh: only the"
  echo "-- old_label_metadata INSERT differs (see harness/gen-patches.sh for why)."
  ups 179 | awk -f "$PATCHES/179-insert-swap.awk"
} > "$PATCHES/179.sql"

# --- 196: seeds every city's config row and keeps the one whose database_name is current_database(). DC's row is
# --- keyed 'sidewalk' (its legacy database name); the sandbox and the eventual prod schema are not, so key the
# --- keep on the row itself.
{
  echo "-- Patched mainline 196.sql (issue #4700), generated by gen-patches.sh: keep DC's config row by its"
  echo "-- database_name ('sidewalk') rather than by current_database(), which the migrated schema never matches."
  ups 196 | sed "s/DELETE FROM config WHERE current_database() != database_name;/DELETE FROM config WHERE database_name <> 'sidewalk';/"
} > "$PATCHES/196.sql"
grep -q "database_name <> 'sidewalk'" "$PATCHES/196.sql" || { echo "196 patch did not apply" >&2; exit 1; }

echo "generated: $PATCHES/26.sql ($(wc -l < "$PATCHES/26.sql") lines), $PATCHES/179.sql ($(wc -l < "$PATCHES/179.sql") lines), $PATCHES/196.sql ($(wc -l < "$PATCHES/196.sql") lines)"
