#!/usr/bin/env bash
# Generates the patches that are mechanical edits of repo evolutions (issue #4700), so the bulk of
# their SQL provably matches the mainline files rather than a hand transcription.
set -euo pipefail
EVODIR=/home/jonf/git/SidewalkWebpage/conf/evolutions/default
PATCHES=/home/jonf/git/dc-migration/patches

ups() { awk '/^# --- !Ups/{flag=1;next} /^# --- !Downs/{flag=0} flag' "$EVODIR/$1.sql" | sed 's/;;/;/g'; }

# --- 26: TIMESTAMP -> TIMESTAMPTZ conversions. DC recorded wall times in US/Eastern, not PST, and
# --- patches/16.sql already created mission with TIMESTAMPTZ, so its block is dropped.
{
  echo "-- Patched mainline 26.sql (issue #4700), generated by gen-patches.sh: 'PST' -> 'US/Eastern'"
  echo "-- (DC's server wrote Eastern wall times), and the mission block is dropped (patches/16.sql"
  echo "-- created mission with TIMESTAMPTZ directly)."
  ups 26 | sed "s/'PST'/'US\\/Eastern'/g" \
         | awk '/^ALTER TABLE mission$/{skip=1} skip && /mission_end SET DEFAULT now\(\);$/{skip=0;next} !skip'
} > "$PATCHES/26.sql"

# --- 179: the CV coordinate fix DC's fork partially backported (its evo 17). Everything verbatim
# --- except the old_label_metadata INSERT: the mainline version gate ('7.12.2') is meaningless for
# --- DC, and DC's fork saved the TRUE pre-fix coordinates, which preclean parked in
# --- dc_old_label_metadata_backup. The recompute UPDATE stays verbatim: it requires
# --- gsv_data.width IS NOT NULL, which is never true for DC (its fork nulled all dimensions), so
# --- it provably no-ops instead of double-transforming the already-fixed coordinates.
{
  echo "-- Patched mainline 179.sql (issue #4700), generated by gen-patches.sh: only the"
  echo "-- old_label_metadata INSERT differs (see harness/gen-patches.sh for why)."
  ups 179 | awk -f "$PATCHES/179-insert-swap.awk"
} > "$PATCHES/179.sql"

echo "generated: $PATCHES/26.sql ($(wc -l < "$PATCHES/26.sql") lines), $PATCHES/179.sql ($(wc -l < "$PATCHES/179.sql") lines)"
