package models.label

import com.google.inject.ImplementedBy
import models.utils.MyPostgresProfile
import models.utils.MyPostgresProfile.api._
import org.locationtech.jts.geom.Point
import play.api.db.slick.{DatabaseConfigProvider, HasDatabaseConfigProvider}

import javax.inject.{Inject, Singleton}

/**
 * A label's position in the panorama and on the map.
 *
 * @param centerlineOffsetM Signed geodesic metres from the label's street's centerline (#2886): + left of the edge's
 *                          digitized direction, - right, None without a position. Only `computeCenterlineOffset` writes it.
 * @param streetSide        The offset with a 1 m floor; generated by the DB, never written from Scala.
 */
case class LabelPoint(
    labelPointId: Int,
    labelId: Int,
    panoX: Int,
    panoY: Int,
    canvasX: Int,
    canvasY: Int,
    heading: Double,
    pitch: Double,
    zoom: Double,
    lat: Option[Double],
    lng: Option[Double],
    geom: Option[Point],
    computationMethod: Option[ComputationMethod.Value],
    centerlineOffsetM: Option[Double],
    streetSide: Option[StreetSide.Value]
)

class LabelPointTableDef(tag: slick.lifted.Tag) extends Table[LabelPoint](tag, "label_point") {
  def labelPointId: Rep[Int]                                  = column[Int]("label_point_id", O.PrimaryKey, O.AutoInc)
  def labelId: Rep[Int]                                       = column[Int]("label_id")
  def panoX: Rep[Int]                                         = column[Int]("pano_x")
  def panoY: Rep[Int]                                         = column[Int]("pano_y")
  def canvasX: Rep[Int]                                       = column[Int]("canvas_x")
  def canvasY: Rep[Int]                                       = column[Int]("canvas_y")
  def heading: Rep[Double]                                    = column[Double]("heading")
  def pitch: Rep[Double]                                      = column[Double]("pitch")
  def zoom: Rep[Double]                                       = column[Double]("zoom")
  def lat: Rep[Option[Double]]                                = column[Option[Double]]("lat")
  def lng: Rep[Option[Double]]                                = column[Option[Double]]("lng")
  def geom: Rep[Option[Point]]                                = column[Option[Point]]("geom")
  def computationMethod: Rep[Option[ComputationMethod.Value]] =
    column[Option[ComputationMethod.Value]]("computation_method")
  def centerlineOffsetM: Rep[Option[Double]] = column[Option[Double]]("centerline_offset_m")
  // GENERATED ALWAYS ... STORED in the DB, and Postgres rejects an explicit value, so `insertProjection` leaves it out.
  def streetSide: Rep[Option[StreetSide.Value]] = column[Option[StreetSide.Value]]("street_side")

  def * = (labelPointId, labelId, panoX, panoY, canvasX, canvasY, heading, pitch, zoom, lat, lng, geom,
    computationMethod, centerlineOffsetM, streetSide) <> ((LabelPoint.apply _).tupled, LabelPoint.unapply)

  def insertProjection = (labelId, panoX, panoY, canvasX, canvasY, heading, pitch, zoom, lat, lng, geom,
    computationMethod, centerlineOffsetM)

  def label       = foreignKey("label_point_label_id_fkey", labelId, TableQuery[LabelTableDef])(_.labelId)
  def labelUnique = index("label_point_label_id_key", labelId, unique = true)
}

/**
 * Companion object with constants that are shared throughout codebase.
 */
object LabelPointTable {
  val canvasHeight: Int = 480
  val canvasWidth: Int  = 720
}

@ImplementedBy(classOf[LabelPointTable])
trait LabelPointTableRepository {}

@Singleton
class LabelPointTable @Inject() (protected val dbConfigProvider: DatabaseConfigProvider)
    extends LabelPointTableRepository
    with HasDatabaseConfigProvider[MyPostgresProfile] {

  val labelPoints = TableQuery[LabelPointTableDef]

  /** Inserts a label point, returning its id; the offset is filled in by `computeCenterlineOffset` afterwards. */
  def insert(point: LabelPoint): DBIO[Int] = {
    (labelPoints.map(_.insertProjection) returning labelPoints.map(_.labelPointId)) += ((
      point.labelId, point.panoX, point.panoY, point.canvasX, point.canvasY, point.heading, point.pitch, point.zoom,
      point.lat, point.lng, point.geom, point.computationMethod, point.centerlineOffsetM
    ))
  }

  /**
   * Recomputes a label point's signed centerline offset against the given edge (#2886); the generated `street_side`
   * follows. Calls the same SQL function as 375.sql's backfill, so a stored value always equals a fresh recompute.
   *
   * @param streetEdgeId The label's `street_edge_id`, the edge the side is relative to.
   * @return Rows updated: 1, or 0 if either id is unknown.
   */
  def computeCenterlineOffset(labelPointId: Int, streetEdgeId: Int): DBIO[Int] =
    sqlu"""UPDATE label_point
           SET centerline_offset_m = label_centerline_offset_m(label_point.geom, street_edge.geom)
           FROM street_edge
           WHERE label_point.label_point_id = $labelPointId
             AND street_edge.street_edge_id = $streetEdgeId"""
}
